name: Visionar
favicon: null
layout_spectrum: 0.0679935785010457
typography_spectrum: 0.6333510677795857
title: Graphic design and website agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.16060239425860345
  lightness: 0.7976478240452707
  saturation: 0.2828449734952301
  rhythmicContrast: 0.5013391438405961
purpose: []
