name: Visionar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50099
title: Graphic design and website agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#ffffff'
    - '#00a5b5'
    - '#767676'
    - '#b1b1b1'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
