name: Visionar
favicon: null
layout_spectrum: 0.0679935785010457
typography_spectrum: 0.6333510677795857
title: Graphic design and website agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#ffffff'
    - '#00a5b5'
    - '#767676'
    - '#b1b1b1'
  brandStrength: 0.5
  lightness: 0.7976478240452707
  saturation: 0.2828449734952301
  rhythmicContrast: 0.5013391438405961
purpose: []
