name: Visionar
favicon: null
layout_spectrum: 0.99249
typography_spectrum: 1
title: Graphic design and website agency
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#636363'
    - '#fd8775'
    - '#19a6a3'
    - '#fff5cf'
    - '#1b1b1a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
